version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # platform: linux/amd64  # Add platform flag here if you're targeting a different architecture
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
